### ISSUE TITLE
Cleanup endpoints

### ISSUE THREAD

**Issue by taliaga** [martel-innovate/eWine-connectivity-manager#3]
As discussed, let's cleanup a bit the endpoints:

networks/ -> List of stored networks in /etc/networks/interfaces.
scan/ -> Scans available network, requires the interface name (e.g wlan0)

If you want, you can add the /interfaces.

Remember the PR for this one.

**Comment by taliaga** [comment]
Feel free to add the "enabled/disabled" capabilities you mentioned either in this same task or in a different one.

**Comment by k33rs** [comment]
Done.
