### ISSUE TITLE
DB issue in fresh install

### ISSUE THREAD

**Issue by taliaga** [martel-innovate/eWine-connectivity-manager#5]
```
$ python wifi_rest.py
Traceback (most recent call last):
  File "wifi_rest.py", line 261, in <module>
    _init_db()
  File "wifi_rest.py", line 52, in _init_db
    db = _get_db()
  File "wifi_rest.py", line 40, in _get_db
    db = g._database = sqlite3.connect(app.config['DB_INSTANCE'])
sqlite3.OperationalError: unable to open database file
```

**Comment by k33rs** [comment]
are you running the application using the interpreter script?
It's supposed to run as sudo.

Also, is the project located at '/home/pi/eWine-connectivity-manager'?
If not, that's why you can't open the .db file, whose path is '/home/pi/eWine-connectivity-manager/wifi_manager/schema/schema.db'

**Comment by k33rs** [comment]
Removed the hardcoded absolute path, now the database should be opened regardless of the project path. You can see the changes in the [last commit][1].

[1]:https://github.com/martel-innovate/eWine-connectivity-manager/commit/63bf34e9e4b131f0067edb6ed7c92a3e22fa1ee0
